version: 1.0
app:
  instances:
    min: 1
    max: 2
  # configure endpoints
  endpoints: public
  version: 
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
